version: "3.7"
services:
  sflog:
    container_name: sflog
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - REACT_APP_GO_SERVER=http://localhost:8080
