# build environment
FROM node:10.16.3-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json

# Install packages
RUN npm install --no-optional
RUN npm update

COPY . /app
RUN npm run build