version: "3"
volumes:
  app-volume:
  le_keys:
services:
  sflbuild:
    build:
      context: ./
      dockerfile: Dockerfile-prod-home
    volumes:
      - app-volume:/app/build
  sflweb:
    image: linuxserver/letsencrypt
    container_name: sflweb
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000 #Maps the container user to the host user instead of root
      - PGID=1000
      - TZ=Europe/London
      - URL=formyer.com
      - SUBDOMAINS=sfl,
      - VALIDATION=http
      - EMAIL=bushcraftparsons@gmail.com #optional
      - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=true #optional
      - STAGING=true #optional change to false for production
    volumes:
      - app-volume:/config/www
      - le_keys:/config
    ports:
      - 443:443
      - 80:80 #allows http validation
    restart: unless-stopped
  sflapi:
    container_name: sflogapi
    build:
      context: ../sflogapi
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - le_keys:/le_keys